/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_sevenzipjbinding_impl_OutArchiveImpl */

#ifndef _Included_net_sf_sevenzipjbinding_impl_OutArchiveImpl
#define _Included_net_sf_sevenzipjbinding_impl_OutArchiveImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_sevenzipjbinding_impl_OutArchiveImpl
 * Method:    nativeSetProperties
 * Signature: ([Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_net_sf_sevenzipjbinding_impl_OutArchiveImpl_nativeSetProperties
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     net_sf_sevenzipjbinding_impl_OutArchiveImpl
 * Method:    nativeUpdateItems
 * Signature: (Lnet/sf/sevenzipjbinding/ISequentialOutStream;ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_net_sf_sevenzipjbinding_impl_OutArchiveImpl_nativeUpdateItems
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     net_sf_sevenzipjbinding_impl_OutArchiveImpl
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_sevenzipjbinding_impl_OutArchiveImpl_nativeClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
